### ISSUE TITLE
Web links in documents point to our github location

### ISSUE THREAD

**Issue by iawells** [lfn-cnti/bestpractices#108]
They should be relative links so that our documents refer to each other in forked repositories properly, otherwise it's hard to check the work you've done in a pull request.

**Comment by iawells** [comment]
Also affects links within branches even within the cnf-wg repo, as all of these links are to the master branch.

**Comment by xmulligan** [comment]
added to the style guide in the contributing.md

**Comment by xmulligan** [comment]
closing as stale
