### ISSUE TITLE
Update Master to Main 

### ISSUE THREAD

**Issue by xmulligan** [lfn-cnti/bestpractices#114]
https://github.com/github/renaming

**Comment by xmulligan** [comment]
https://inclusivenaming.org/

**Comment by xmulligan** [comment]
https://inclusivenaming.org/language/word-list/

**Comment by taylor** [comment]
Branch renamed.  All open PRs automatically updated to reference `main`.  

Everyone with a local checkout will need to update manually or do a new clone.

@xmulligan I think this issue can be closed.

**Comment by iawells** [comment]
(I did check; lgtm)
