### ISSUE TITLE
Explain how you can submit a change on a PR

### ISSUE THREAD

**Issue by iawells** [lfn-cnti/bestpractices#132]
Github lets you add change proposals to PRs, which is more efficient than reading someone's comment and writing up the change yourself.  However, it's caught out several people, me included - it's not obvious you can do this if you've never done it before.

Add a note to the reviewer help to explain how this works and how to do it, and that changes are in fact welcome and preferred over comments when you know exactly what change you're looking for.

**Comment by xmulligan** [comment]
do you want this in the contributing docs or someplace else?

**Comment by jeffsaelens** [comment]
Contributing.md would make sense to me. It's a simple but effective way for those who are looking to engage but aren't super confident on how or where to get involved. To @iawells point though, it's not super intuitive. Maybe Ian you snap a couple of screenshots and make a mini-guide in the discussions section?
