### ISSUE TITLE
Update reference urls for CNF Test Suite

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/bestpractices#141]
# Update reference urls for CNF Test Suite

## Reason for change
- the repo name for the CNF Test Suite has been changed from cnf-conformance to `cnf-testsuite`.
- the super linter will fail if it sees references files in cnf-conformance

### Changes requested
- update all files that should point to the new repo `cnf-testsuite`

### How this will be tested
- The super linter should not show "dead link" errors pointing to files in the cnf-conformance repo

**Comment by lixuna** [comment]
I'll work on this and create a PR

**Comment by taylor** [comment]
Some work done in PR https://github.com/cncf/cnf-wg/pull/140

**Comment by xmulligan** [comment]
@lixuna can this be closed or is there more to do?

**Comment by xmulligan** [comment]
closing as stale
