### ISSUE TITLE
Proposal: Switch from org or individual to individual with org affiliation listed.

### ISSUE THREAD

**Issue by taylor** [lfn-cnti/bestpractices#143]
Proposal: Switch from org or individual to individual with org affiliation listed.

This will better represent our community which consists of individual contributors. It encourages participation and contributions regardless of your organization affiliation. If needed we can still make decisions based on representation of a single org based on the listed org for each individual.

Reference:
- https://github.com/cncf/sig-app-delivery/blob/master/operator-wg/charter.md#interested-parties
- https://github.com/cncf/toc/blob/main/workinggroups/serverless.md#initial-interested-parties
- https://github.com/cncf/toc/blob/main/workinggroups/storage.md#initial-interested-parties
- GitOps WG has individuals with the company name.  See https://docs.google.com/document/d/11EZfvB2FFI837nMmArnyv-wizsIJvc-4_xdgfoUXF4o/edit#heading=h.665fh095a0wv
- same for the operator WG https://github.com/cncf/sig-app-delivery/blob/master/operator-wg/charter.md#interested-parties

_Originally posted by @taylor in https://github.com/cncf/cnf-wg/discussions/126_

**Comment by xmulligan** [comment]
this could also address #87

**Comment by taylor** [comment]
Addressed in merged #144
