### ISSUE TITLE
Define "Kube-native" in the glossary

### ISSUE THREAD

**Issue by xmulligan** [lfn-cnti/bestpractices#159]
Kube-Native has been used through some of our work, see #95 for one example, but has not yet been defined. It is also currently listed as TBD in the glossary https://github.com/cncf/cnf-wg/edit/main/doc/glossary.md.

It would be great to have a defintion so we are all on the same page.

**Comment by CsatariGergely** [comment]
I do not think that we should define Kube-native. What would Kube-native mean? Things that made to run on Kubernetes? This definition assumes that Kubernetes itself is not evolving what is far from reality.
