### ISSUE TITLE
[Presentation] prepare slides and recording for CNF WG intro at KubeCon NA 2021

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/bestpractices#191]
Title: [KubeCon NA 2021] Intro & Deep Dive to the CNF WG

Speakers: CNF WG Co-chairs, @iawells @jeffsaelens @taylor 

Event details: 
- Friday, October 15 • 5:25pm - 6:00pm PDT (35 minutes total, including time for interactive Q&A)
- https://sched.co/lV9e

Tasks: 
- [x]  Pre-Recorded Video File Submission 
- [ ]  Presentation Slides Upload Deadline: Friday, October 1 by 11:59 PM PDT

**Comment by lixuna** [comment]
🥳 Pre-recorded video has been submitted to the CNCF Content Team

**Comment by taylor** [comment]
13pts

**Comment by taylor** [comment]
Effort estimate: 

@taylor 13pts

**Comment by lixuna** [comment]
Yes, if we were to use the fibonacci sequence to estimate the level of effort to put together this material, practice, rehearse and record, I'd agree that it was 13 points of effort.

(ie. on a scale from 0,1,2,3,5,8,13,21)

**Comment by jeffsaelens** [comment]
It was definitely more challenging than I had first anticipated.

**Comment by iawells** [comment]
Yes, we definitely need a word with the scrum master.

Anyway, I think we can close this issue now...

**Comment by iawells** [comment]
Except you haven't uploaded the slides yet, have you...

**Comment by lixuna** [comment]
To do:
- Upload Presentation Slides (Deadline: Friday, October 1 by 11:59 PM PDT)

**Comment by taylor** [comment]
uploaded
