### ISSUE TITLE
Lower the number of required approvers

### ISSUE THREAD

**Issue by iawells** [lfn-cnti/bestpractices#218]
Given the number of active members, we should lower the required number of approvers from 5 to 3.

**Comment by electrocucaracha** [comment]
Maybe we can enforce this through [Required number of approvals before merging](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule) from Branch protection rule.
