### ISSUE TITLE
Add title to exceptions doc

### ISSUE THREAD

**Issue by taylor** [lfn-cnti/bestpractices#227]
The document https://github.com/cncf/cnf-wg/blob/main/cbpps/0003-exceptions.md was merged but is missing a few things including the title
>CBPP-NNNN: Your short, descriptive title (TEMPLATE)

**Comment by electrocucaracha** [comment]
These are some possible options:

* Expressing the best practice exception
* Document exceptions to following a best practice

**Comment by electrocucaracha** [comment]
@iawells those are some options that we proposed during the weekly meeting, can you check them?
