### ISSUE TITLE
Update best_cnf_dev.md to match categories in CNF Test Suite

### ISSUE THREAD

**Issue by taylor** [lfn-cnti/bestpractices#228]
The categories in [best_cnf_dev.md](docs/best_cnf_dev.md) are no longer in sync with the [test categories](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) in the related CNF Test Suite.  

TODO:
- [x] review https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md
- [x] determine if those categories work for the CNF WG for now
- [x] Update  [best_cnf_dev.md](docs/best_cnf_dev.md)  to match https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md

**Comment by tomkivlin** [comment]
NOTE: this issue is just about the ToC, not about the contents of each section (should be handled as a larger number of separate issues).

**Comment by lixuna** [comment]
Draft started in https://hackmd.io/RbDU2xPjTyS1NvyKLZ8DpA

**Comment by lixuna** [comment]
merged in https://github.com/cncf/cnf-wg/pull/239
