### ISSUE TITLE
Move best practices, user stories and use case folders under docs

### ISSUE THREAD

**Issue by taylor** [lfn-cnti/bestpractices#247]
TODO: 
- [x] move user stories https://github.com/cncf/cnf-wg/tree/main/user-stories under docs
  - [x] Update all links in repo to point to new location
- [x] move use case https://github.com/cncf/cnf-wg/tree/main/use-case under docs
  - [x] Update all links in repo to point to new location
- [x] move best practice folder https://github.com/cncf/cnf-wg/tree/main/cbpps under docs
  - [x] Update all links in repo to point to new location

**Comment by ShlokMohanty** [comment]
@taylor can you please assign this task to me as i am very much interested in improving the CNCF docs

**Comment by electrocucaracha** [comment]
@ShlokMohanty any progress on this? Let us know if you need some guidance.

**Comment by ronit-nandwani** [comment]
@electrocucaracha Can I pick it up?

**Comment by ShlokMohanty** [comment]
@ronit-nandwani yeah sure if you could complete the work then you can ask @electrocucaracha to assign it to you

**Comment by ShlokMohanty** [comment]
> @ShlokMohanty any progress on this? Let us know if you need some guidance.

Just need a bit of time if it works for you ?

**Comment by ronit-nandwani** [comment]
@electrocucaracha Created a PR for this issue, do take a look and let me know if it looks good?
PR Link: https://github.com/cncf/cnf-wg/pull/263

**Comment by Azanul** [comment]
@electrocucaracha All the TODOs in the issue have been taken care of, I think this issue can be closed.
