### ISSUE TITLE
Telco Community Gathering - KubeCon EU 2023

### ISSUE THREAD

**Issue by taylor** [lfn-cnti/bestpractices#256]
<p>
<table>
<tr>
<td>
<img alt="visual representation of the telco community gathering with tulips in Amsterdam with people sitting around together" src="https://user-images.githubusercontent.com/26697/225457326-9b63717c-023f-4dec-966d-a12793188df0.png" width="200" height="200"/>
</td>
<td valign="center" align="center" border=0 style="border-style: hidden;">
<b>Telco Community Gathering - KubeCon EU 2023</b><br/>
<b>Tuesday, April 18th, 2023</b><br/>
<b>2:00-5:00 PM CEST</b><br/>
<b>Taki Taki</b><br />
Address: <a href="https://goo.gl/maps/8USfbrArH7g6CjGw8">Coronalab.eu Amsterdam Zuid, <br />Hogelandplein 1a, 1079 RZ Amsterdam, Netherlands</a>
</td>
</tr>
</table>
</p>

**What is it?**
A time (and place) during KubeCon where people can meet with the CNCF Telco community, including:

- [CNF Working Group](https://github.com/cncf/cnf-wg) - Documenting use cases, best practices, and collaborating with complimentary communities
- [CNF Certification](https://www.cncf.io/certification/cnf/) - What it is about and how to get started, including hands-on support
- [CNF Test Suite](https://github.com/cncf/cnf-testsuite) - Using it as a development and ops tool, integrate into CI systems
- Birds of a Feather presentations - short 5-10 minute presentation on topic of interest
- Open discussion time for various topics such as a wider discussion about CNF/Platform certification/interoperability approaches, problems, processes, vendor(s) involvements, communities such as Sylva, LFN Anuket, etc.

**When is it?**
Tuesday, April 18th, 2023 - In the afternoon following Cloud Native Telco Day

**Where is it?**
Taki Taki Co-working: 
Hogelandplein 1a, 1079 RZ Amsterdam, Netherlands

<img alt="map showing walking directions from RAI to Taki Taki Co-Working" src="https://user-images.githubusercontent.com/26697/230246177-8262bac4-54bd-4feb-bdaf-6a918a013913.png" width="200" height="319"/>

**Who should attend?**
Registered KubeCon attendees (up to 50 people)

**How do I sign up?**
RSVP to save your seat at https://forms.gle/WqMmRNCBgHTcx6iM7

----

**What to do before the event**

If you have 5 minutes (or less lighting talk), a topic idea for open discussion, or a working session tasks you would like to suggest (such as contributing a telecom term to the CNCF glossary) post a comment to this issue.  You can also start a discussion in the [Discussions forum in this thread](https://github.com/cncf/cnf-wg/discussions/257).

**What to expect at the event**

There will be an area designated for our community gathering.  You should be prepared to show your badge or some id related to your RSVP.  There is a max of 50 people for this event and those that RSVP have first access with any that were not RSVP allowed as long as there is still room.

- Topics can be proposed upon arrival at the gathering as well including for the BoF lighting talks until we are full
- There will be drinks (both alcoholic and non-alcoholic including drink tickets for those who RSVPd) and snacks available
- There will be internet and ability to present on a screen

---

**Agenda**

- Birds of Feather - (up to 5 minute talks)
   - TBD (add your topic in the comments of this issue)
- Topic open discussions.  Ideas suggested so far:
   -  "telco validation/certification and the flexibility of CNI plugins"
   - "Probing CNFs in containerised environments"
   - Nephio
   - Anuket
   - Private 5G with a raspberry pie
   - Telco validation/certification and the flexibility of CNI plugins - Cilium / eBPF for Telco workloads
   - Open Discussion over CAMARA Exposure Gateway
   - Consider CNF on-boarding best practices in WG
   - Kubernetes LTS mechanism, the alignment in telco multi-vendor interoperability
- Working session(s)
   - Draft + Submit Best practice PRs
   - Contribute to [CNCF glossary project](https://github.com/cncf/glossary)

Note: The open discussion and working session time may overlap

**Comment by tomkivlin** [comment]
Have mentioned to Isovalent as they have been talking to us about Cilium / eBPF for Telco workloads.  Depending if they can make it we could have a discussion about e.g. "telco validation/certification and the flexibility of CNI plugins".

**Comment by taylor** [comment]
@tomkivlin please invite and tag some folks in this issue

**Comment by taylor** [comment]
@nickolaev

**Comment by taylor** [comment]
Please fill out this form if interested in the event https://forms.gle/bam6VEk22B5Q5Vy7A

**Comment by lixuna** [comment]
RSVP status as of today:
- 24 in-person
- 2 virtual (if available) 

Proposed Topics for discussion:
- Engagement with Sylva
- Sylva 
- What is the perception of Nephio ?
- Open Discussion over CAMARA Exposure Gateway (want to hear community member's idea and understanding over this)
- Consider CNF on-boarding best practices in WG
- do we really need several CNF conformance programs?

**Comment by lixuna** [comment]
RSVP status as of today (March 26):
- 29 in-person
- 4 virtual (if available) 

Number of possible topic ideas people have: 10-12, including:

Sylva
- Quick overview of Sylva project
- [Vuk Gojnic] Engagement with Sylva
- [Guillaume Nevicato] 1. Sylva 
- [Thomas Morin] Sylva, what is it made of and how

Nephio
- Quick overview of Nephio
- [Guillaume Nevicato] 2. What is the perception of Nephio ?

and more:
- Quick overview of Anuket
- Private 5G with a raspberry pie
- Telco validation/certification and the flexibility of CNI plugins -  Cilium / eBPF for Telco workloads
- [Dan Finneran] “Generally there for learning about Cloud Native challenges!”
- [Shuting Qing] Open Discussion over CAMARA Exposure Gateway (We don't quite know about this part, but we want to hear community member's idea and understanding over this)
- [Victor Morales] Consider CNF on-boarding best practices in WG
- [chaoyi huang] Kubernetes LTS mechanism, the alignment in telco multi-vendor interoperability
- [Tom Kivlin] Probing CNFs in containerised environments

**Comment by tomkivlin** [comment]
@lixuna I added one to the original post in the thread (sorry, wasn't sure where to put it):

"Probing CNFs in containerised environments"

**Comment by taylor** [comment]
Taki Taki Co-working: Hogelandplein 1a, 1079 RZ Amsterdam, Netherlands

<img alt="map showing walking directions from RAI to Taki Taki Co-Working" src="https://user-images.githubusercontent.com/26697/230246177-8262bac4-54bd-4feb-bdaf-6a918a013913.png" width="200" height="319"/>

**Comment by lixuna** [comment]
RSVP status as of today (April 11):

- 42 in-person (50 max)
- 4 virtual (if available)

Number of possible topic ideas people have: 10-12, including:

Sylva

- Quick overview of Sylva project
- [Vuk Gojnic] Engagement with Sylva
- [Guillaume Nevicato] 1. Sylva
- [Thomas Morin] Sylva, what is it made of and how

Nephio

- Quick overview of Nephio
- [Guillaume Nevicato] 2. What is the perception of Nephio ?

and more:

- Quick overview of Anuket
- Private 5G with a raspberry pie
- Telco validation/certification and the flexibility of CNI plugins - Cilium / eBPF for Telco workloads
- [Dan Finneran] “Generally there for learning about Cloud Native challenges!”
- [Shuting Qing] Open Discussion over CAMARA Exposure Gateway (We don't quite know about this part, but we want to hear community member's idea and understanding over this)
- [Victor Morales] Consider CNF on-boarding best practices in WG
- [chaoyi huang] Kubernetes LTS mechanism, the alignment in telco multi-vendor interoperability
- [Tom Kivlin] Probing CNFs in containerised environments
- Certification help

**Comment by lixuna** [comment]
TBD:
- will this meeting be livestreamed? tbd
- will this meeting be recorded and published? no

**Comment by taylor** [comment]
We do not plan to publish a recording of this event



> TBD:
> 
> * will this meeting be livestreamed? tbd

This is unlikely.  We will need to visit the venue to decide if it is feasible.  

> * will this meeting be recorded and published? no

No plans to publish a recording

**Comment by lixuna** [comment]
RSVP status as of today (April 13):

- 44 in-person (50 max)
- 4 virtual (livestream is unlikely, no plans to record the meeting, meeting notes will be available)

**Comment by taylor** [comment]
Please use the address Hogelandplein 1a, 1079 RZ Amsterdam, Netherlands to find the event with Google Maps.  The name Taki Taki will show the wrong address.

**Comment by taylor** [comment]
Live shared notes - https://etherpad.wikimedia.org/p/Telco_Community_Gathering_-_KubeCon_EU_2023-04-18

**Comment by taylor** [comment]
The name Taki Taki will show the wrong address in google maps.  The Taki Taki is located at the same address as: Coronalab.eu Amsterdam Zuid, Hogelandplein 1a, 1079 RZ Amsterdam, Netherlands

https://goo.gl/maps/8USfbrArH7g6CjGw8

**Comment by taylor** [comment]
Taki Taki is on the other side of a construction area from Happy Italy restaurant

![image](https://user-images.githubusercontent.com/26697/232744737-53e4620e-8fa6-45cc-8b51-fc72f32a86ca.png)

**Comment by lixuna** [comment]
Event stats:
- 57 in-person attendees
- 5 presentations
- shared meeting notes available at https://etherpad.wikimedia.org/p/Telco_Community_Gathering_-_KubeCon_EU_2023-04-18
