### ISSUE TITLE
[Documentation] Update GitHub description, README, etc to reflect new CNTI program

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/bestpractices#308]
**Describe the update:**
- Update GitHub description, README, etc to reflect new CNTI program
- https://wiki.lfnetworking.org/display/LN/Best+Practices

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))
- This meeting used to be called: CNCF CNF WG 
- This meeting is currently called: LFN's CNTI Best Practices focus area

**Additional context**
- https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592
- #304 
- Remove references to CNCF and CNCF CNF Working Group (WG) in documentation

**Comment by wjsvec** [comment]
I would like to work on this issue! Could you please assign it to me? 😊

**Comment by wjsvec** [comment]
Update Documentation progress on tasks
- [x] GitHub description
- [x] README.md
- [ ] CONTRIBUTING.md

**Comment by lixuna** [comment]
Description has been updated: 
<img width="320" alt="Screenshot 2024-02-26 at 10 19 49 AM" src="https://github.com/lfn-cnti/bestpractices/assets/11701267/d55cd32a-cdb2-4730-bf03-8684f01a10e2">

**Comment by lixuna** [comment]
To do: 

This section of the [README](https://github.com/lfn-cnti/bestpractices?tab=readme-ov-file#cloud-native-telecom-initiative-cnti-best-practices) requires updates: 

> The [CNF Test Suite](https://github.com/cncf/cnf-testsuite) will support testing a set of these best practices to allow developers and network operators to evaluate how well a network application follows cloud native principles and best practices. Proposals which have been adopted by the CNF WG are listed in the [CNF Best Practice Proposal](https://github.com/lfn-cnti/bestpractices/blob/main/doc/cbpps) folder.

**Comment by lixuna** [comment]
> Updated in #328 
> 
> This section of the [README](https://github.com/lfn-cnti/bestpractices?tab=readme-ov-file#cloud-native-telecom-initiative-cnti-best-practices) requires updates:
> 
> > The [CNF Test Suite](https://github.com/cncf/cnf-testsuite) will support testing a set of these best practices to allow developers and network operators to evaluate how well a network application follows cloud native principles and best practices. Proposals which have been adopted by the CNF WG are listed in the [CNF Best Practice Proposal](https://github.com/lfn-cnti/bestpractices/blob/main/doc/cbpps) folder.

**Comment by lixuna** [comment]
Closing this issue as the README and description have been updated.

See #324 for updating the contributing guide
