### ISSUE TITLE
"Do not run containers with the privilege flag" as a best practice

### ISSUE THREAD

**Issue by iawells** [lfn-cnti/bestpractices#67]
I believe we could add a best practice for 'don't use privilege'.  We could add a user story to justify it (something about making the platform robust to application behaviour) but I believe the best practice can stand alone.

The higher level principle is:
- Principle of least privilege (discussion https://github.com/cncf/cnf-wg/discussions/28)

See discussion https://github.com/cncf/cnf-wg/discussions/25 for not running containers with privilege flag.

**Comment by electrocucaracha** [comment]
@iawells correct  me if I'm wrong, but this user story will only cover the [Pod definition](https://kubernetes.io/docs/concepts/workloads/pods/#privileged-mode-for-containers)? are you considering to include the [execution of services with a non-root user practice ](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user). Maybe it would be worth it to mention some efforts like [usernetes](https://github.com/rootless-containers/usernetes), [distroless](https://github.com/GoogleContainerTools/distroless) and [katacontainers](https://katacontainers.io/) which can be related to that topic.

**Comment by taylor** [comment]
Related Github discussion https://github.com/cncf/cnf-wg/discussions/28

**Comment by iawells** [comment]
I was thinking specifically about the k8s-granted privilege use case here.  What you're talking about are probably not going to turn up in the same best practice, nor be driven by the same use case.

I'm trying to stick to the rules that that the design is dictated by the requirements, but the requirements should not dictate unnecessary design choices.

- The user story says what you're trying to achieve and why (in this case I think we would go with 'a team is responsible for its own mistakes and an operator must be able to find the responsible team' - so an app breaking the platform through using privilege confuses that, because the app team breaks the platform and the platform team gets blamed)

- A design would suggest a way of implementing something that solves the user story, and I think a number of your suggestions might work there (along with other options).  It might or might not cover only the pod definition, and it might consider things like katacontainers.  It will almost certainly speak of pod privileges (both system-root and CAP_*), since pods with that sort of privilege can always break platform components, and that should not be possible.

  I think the 'non-root user' part is not going to work in response to the above user story, though.  It's more a 'least privilege' security requirement directed at the CNF developer in order to make more secure CNFs - so it would be driven by a different user story than the example I gave.  It doesn't actually grant you any more power over the platform or make you any more destructive if you have the in-container UID 0 (which typically is not the system root).

- A best practice would be the implications our preferred design, which for whatever reason we considered to be better than the others.

I think your suggestions are things that a design might propose, if that helps you think about it.  The user story would just say 'there's a problem'.

**Comment by michaelspedersen** [comment]
While "don't use privilege" should be enough, I guess it ties in to the (common) platform requirement of immutable infrastructure. I'm having a hard time thinking how privilege can be granted to a CNF, while still ensuring that this infrastructure remains unchanged.

This changes a bit when using Katacontainers or similar, where a CNF could utilize privilege without impacting the infrastructure, but this would only ever be allowed when there is a layer of virtualization between the two.

**Comment by xmulligan** [comment]
from 15/02 meeting
It should also be pushed towards the multi tenancy use case as this is a benefit of Kubernetes
Should we separate out the runtime conversation from privilege?
It's not about privilege, but rather about what it allows

**Comment by iawells** [comment]
So there are two points that came of the meeting that need to be answered by the use case document:

1. What is it you need to do with privilege?  Why can't you do it any other way?  (Another way of phrasing this is 'if you aren't going to use privilege you need to be able to do everything that privilege would normally be used for, but without actually using privilege')
2. Rephrasing Michael's point above, what if the runtime you're using doesn't offer privilege?  Are we dictating runtimes, either by name or by feature?

**Comment by xmulligan** [comment]
[Tal]
one idea is to centralize privilege, but that centralized service might not be available everywhere
or minimize and isolate as much as possible

**Comment by iawells** [comment]
Istio/Envoy is an interesting example here.  It needs privs to do what it needs to do to the network.  But it effectively does that in order to delegate the effects to _unprivileged_ applications.

So if you consider it a part of the _platform_ component then it makes sense - the platform manages things that can break the platform (as anything with privs can) and delegates APIs that _can't_ break the platform to the end user's apps.

It would not make as much sense if the _application_ provided Istio as part of its code, because then the _application_ would need privs.  Did the app dev change Istio?  Is it doing dangerous things?  The platform team can't know, and so it _could_ endanger the platform stability.

**Comment by manuelstein** [comment]
virtualdevice plugins for GPU usage are trying to isolate workloads on GPUs. So, depending on what the CNF needs to do (FPGA, DPDK, NIC, SR-IOV function, etc.), could it get its job done by gaining exclusive access to a k8s virtual resource or a slice of it?

**Comment by iawells** [comment]
> virtualdevice plugins for GPU usage are trying to isolate workloads on GPUs. So, depending on what the CNF needs to do (FPGA, DPDK, NIC, SR-IOV function, etc.), could it get its job done by gaining exclusive access to a k8s virtual resource or a slice of it?

I think this is a sensible pattern (it may not be the only pattern, but it's a good one).  If you have two CNFs playing with the same resource simultaneously there's a very good chance it will end up in a state that is no good for either of them.  And if your level of granularity is to give multiple CNFs access to all the hardware (which is roughly the level at which today's conatiner privileges operate) then you don't know if they're playing with only the bit they should be using or fighting with each other (and the platform itself).

So that might be our user story:

- Base premise: when something goes wrong we know how to fix it
- a component (plaform or CNF) should be able to do its job without its behaviour being affected by another component, so that when it goes wrong it's only got itself to blame
- we should delegate control of specific resources to one thing if it's critical to its success
- delegation of hardware resources is the responsibility of the platform, so its job is to cleanly delegate control over precisely the resources needed to get a job done to exactly one application (and, similarly, not delegate ones it needs to successfully run itself)

**Comment by electrocucaracha** [comment]
That's a good point @manuelstein, Kubernetes Device plugins [not only requires privileges to operate (registering and monitoring PFs/VFs)](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#device-plugin-deployment), sometimes Pods need elevated permissions to bind them. Intel QuickAssist is a good example of that behavior as well, it uses a [limit](https://github.com/intel/kubernetes-qat-envoy/blob/main/deployments/boringssl-envoy-deployment.yaml#L103) to request HW resources(VFs/PFs) to the Device plugin but also needs a[ privileged permissions ](https://github.com/intel/kubernetes-qat-envoy/blob/main/deployments/boringssl-envoy-deployment.yaml#L89-L90)to bind the HW resource.

**Comment by iawells** [comment]
> I'm having a hard time thinking how privilege can be granted to a CNF, while still ensuring that this infrastructure remains unchanged

> Kubernetes Device plugins not only requires privileges to operate (registering and monitoring PFs/VFs), sometimes Pods need elevated permissions to bind them

So these two things go hand in hand, and they help with least-privilege, but it's what I commented above.

Platforms _delegate_ functionality to apps, and the functionality has to be delegated in such a way that the app can get its job done, but it isn't enough functionality for one app to interfere with another app or the platform.  So, I can stop _my_ containers, perhaps - that is given to me - but I can't stop other apps' containers.  I can play with _my_ network interfaces if it doesn't affect the networking of others.   I can play with the files in _my_ container filesystem, but not files on the host.  What we choose to delegate and how is what determines how 'least' your privilege in the app can be (that is: the more fine-grained, the better, to a point); but it also ensures that the app never has the power to do what it should not - there is an upper limit.

Things like device plugins can acceptably use dangerous, platform-altering privilege _if they are a part of the platform_, because that's literally the platform's job - it makes containers (apps can't make containers), it separates app networking (apps can't do that), and so on; it's already doing things that it would never let applications do already.  if the platform goes wrong because a high privilege component in the platform broke it, then it's the platform developers at fault and the platform developers' task to fix things.

This upper level of privilege comes back to responsibility.  As a platform maintainer, I accept that the platform will break if _I_ didn't do _my_ job correctly.   But it should never break because _someone else_ didn't do _their_ job correctly.

It also makes sense to keep platform components at least-privilege levels - that's good engineering practice - but the upper bound of their privilege is not limited like it would be with the application.

**Comment by wvwatson** [comment]
*least capabilities* within non or 'unprivileged' processes, can be a more fine grained version of this best practice ... especially for networking/bpf cnfs:
https://man7.org/linux/man-pages/man7/capabilities.7.html

**Comment by iawells** [comment]
eBPF as an example: the problem with eBPF is that to use it you need a really really broad grant of privs - capabilities are typically host-wide.  In much the same way that there's a source-based routing CNI maybe there should be an eBPF one.  The point being, if you have a bit of code to proxy what you're allowed to do via APIs, then it can let you do more specific things ('you can change eBPF programs in a certain part of the netstack, but you can't change namespaces' e.g.).

('APIs' here don't necessarily have to be 'k8s APIs' - they could be a service Unix socket inside the pod, for instance.  Since the thing you're changing is specific to (and local to) the pod, it makes more sense to put the API endpoint where only relevant code can get hold of it, rather than on the network where you have to deflect calls from everyone else.)

**Comment by taylor** [comment]
Included in CNF Certification as an essential test https://github.com/cncf/cnf-certification/blob/main/docs/CNFCertification-1.0-beta.md#privileged-containers-kubescape

**Comment by electrocucaracha** [comment]
This is the [draft](https://docs.google.com/document/d/1h7SHKjd_3fx8kFBtN9gSdS45z5BTZh1zYeBF4noWZ2Q/edit?pli=1) document for this issue

**Comment by tomkivlin** [comment]
Closed by #250
