### ISSUE TITLE
We need a glossary

### ISSUE THREAD

**Issue by iawells** [lfn-cnti/bestpractices#82]
Common terms likely to be used in multiple use cases or in best practices should have a glossary.  That way, many use cases can do without a glossary because the terms will be globally defined.

**Comment by jeffsaelens** [comment]
I'll start working on a PR over the next week or so. I'll take an initial stab at what the list should contain, and pull from various other repos/projects for existing definitions where possible. I'm assuming this is for things like "Kube-Native" ?

**Comment by jeffsaelens** [comment]
Opened PR #89 for this issue.
