### ISSUE TITLE
Update charter with org-merge voting rules

### ISSUE THREAD

**Issue by iawells** [lfn-cnti/bestpractices#83]
From the discussion, the text we like most is:

> As an aside, note that this is more about the reputation of this group being co-opted in the future than it is about it being seen as a mouthpiece for a vested interest in the present. If it's obviously a mouthpiece, that's an issue, but it will impact our reputation and therefore adoption of our recommendations. If our group is co-opted in the future, however, then a group will be able to take advantage of our established reputation.
> 
> 1. Define representation groups that we wish to control representation on. For instance: one chair per independent organisation, 30% of community votes, 30% of tech leads (to avoid majorities of conspirators).
> 2. A organisation is defined as a single company.
> 3. If a member (define 'member') raises a concern of independence: first they must demonstrate a relationship between organisations that lead to the conclusion they should be treated as a single organisation (e.g ownership, contractor-contractee); second, the relationship will be debated, since this does not necessarily demonstrate that the organisations are acting together; and third, action will be taken only if a majority of uninvolved members (choose your membership set and quorum here) votes for it. The action would be that the multiple entities would be considered one organisation under the charter.
> 4. If, through this process, an organisation becomes overrepresented, the seats for that organisation will all be put up for a special election. The seats are open to all members, both previous holders and any other nominees.
> 5. In any elections (presuming we use STV or something similar), the members with least votes in an overrepresented group will be excluded from election (this should already be in some other part of the charter). Where there are multiple candidates with the same number of least votes, it's a coin toss (ditto).
> 6. The decision on independence or dependence may be revisited after a period of not less than three months. A member may raise it for discussion and the process in point 3 shall be repeated. No immediate re-election of members shall occur if the organisations now are deemed independent; this will be taken into consideration in the next natural election cycle.
> To game the above rules, you'd require a majority of the membership conspiring against some part of the community that had overrepresentation if and only if it were considered a bloc, and that bloc would need some corporate relationship, so it would be an unproductive thing to try and do unless a real concern existed. (I can't claim 'everyone not in my company is conspiring against me', for instance, because I haven't got valid grounds to raise the concern.)
> 
> It does not present multiple independent blocs agreeing to vote in concert. What prevents that is a healthy and diverse membership, and there's nothing the rules can do about that.
>

**Comment by taylor** [comment]
Not sure if PR #99 covered everything here. Since it was linked though Github auto closed this issue.

@iawells review ☝️

**Comment by iawells** [comment]
It covered everything this lists, yes (I reworded a bit).  What it doesn't cover is 1-company 1-vote or how block-voting for tech leads can be accomplished if we remove one-company one-vote.
