### ISSUE TITLE
Limit line length in .md files

### ISSUE THREAD

**Issue by iawells** [lfn-cnti/bestpractices#91]
I suggest we limit line length in MD files to 80 characters.

Now, I know that modern editors will word wrap MD files and I know that the MD format does not care about line length.  However, github is making some really hard to interpret diffs of files when they have long line lengths in them.

I suggest we note this in our style guide and add CI to check for it on new pull requests.

**Comment by xmulligan** [comment]
Will be decided upon in a month. Are there any examples we can find that show how it works?

**Comment by xmulligan** [comment]
Maybe we can use the Github Super-linter https://github.com/github/super-linter

**Comment by taylor** [comment]
This was disabled in the #120 PR.

close this?  @iawells

**Comment by iawells** [comment]
Wont be fixed for now. Impprves diffs and causes other problems in turn.
